### PR TITLE
Screenshots uploaded.

### LINKED ISSUE #100: Add screenshots to README and docs
A few screenshots could make the tool more attractive. Currently, there is no impression given on how it looks like in action.

### PR DESCRIPTION
**Pull request by Rishav1707**
## This PR closes the following issue:
closes #100 

## Changes made:
- Added the screenshots in the `readme.md` file.

### CODE REVIEW

**Comment by mlange-42** [comment]
Seems like this was a misunderstanding.

I don't see a lot of use in adding a screenshot **of** the docs. I thought of adding something that shows output of the too, like this:

grafik

**Comment by Rishav1707** [comment]
> Seems like this was a misunderstanding.
> 
> I don't see a lot of use in adding a screenshot **of** the docs. I thought of adding something that shows output of the too, like this:
> 
> grafik

ok I will change it into this image

**Comment by mlange-42** [comment]
Well, if I wanted to include this one I would just add it.

I think the screenshot should be tailor-made for that purpose, with more structured time bars and meaningful project names (cropped them for privacy reasons here)

**Comment by Rishav1707** [comment]
@mlange-42 Please review my changes...

**Comment by mlange-42** [comment]
Sorry, but I can just repeat this:

> Well, if I wanted to include this one I would just add it.

> I think the screenshot should be tailor-made for that purpose, with more structured time bars and meaningful project names (cropped them for privacy reasons here)

**Comment by Rishav1707** [comment]
> Sorry, but I can just repeat this:
> 
> > Well, if I wanted to include this one I would just add it.
> 
> > I think the screenshot should be tailor-made for that purpose, with more structured time bars and meaningful project names (cropped them for privacy reasons here)

What do you mean by tailor-made screenshots?

**Comment by mlange-42** [comment]
I mean make/fake a dataset with some nicely structured and named entries. Like work from 9-16 with maybe 2 pauses, some evening activity, maybe hiking or visiting grandma on the weekend... something like that.

Also, below the week report is a list of the projects with colors as well as the time spent on them. They should have names that people can associate with something, and nice colors.

In the day report, which would also be worth a screenshot, the note for each entry is also shown. So this should also have some nice content.

**Comment by mlange-42** [comment]
I think if you are not a user of `track`, you won't be able to make a useful screenshot.
Closing this. Feel free to re-open or make a new PR in case I'm wrong.

**Pull request closed without merging**
